version: '3.1'

services:
  backend:
    container_name: backend
    build:
      context: ./backend  
      dockerfile: Dockerfile
    image: backend:1.0
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      RUN_MIGRATIONS: ${RUN_MIGRATIONS}
    depends_on:
      - db

  frontend:  
    container_name: frontend
    image: frontend:1.0
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
    depends_on:
      - backend  

  db:  
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
      
volumes:
  postgres-data: